#!/usr/bin/env php
<?php
/**
 * PHP Class Generator 1.0.0
 *
 * This software is licensed under MIT License
 * 
 * @author    Kazuyuki Hayashi <hayashi@valnur.net>
 * @copyright Copyright (c) 2012, Kazuyuki Hayashi
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */

use KzykHys\ClassGenerator\Console\Application;

require_once(__DIR__.'/vendor/autoload.php');

$app = new Application();
$app->run();